using System;
using System.Collections.Generic;
using System.Text;

namespace ai_scheduler.src
{
    public enum Operation
    {
        TRANSFORM,
        TRANSFER
    }

    public enum ResourceKind
    {
        Raw,
        Created,
        Waste
    }

    public class Constants
    {
        public double GAMMA = .9;
        public int SEARCH_DEPTH = 5;
        public int X_0_LOGISTICS_FN = 0;
        public int K_VAL_LOGISTICS_FN = 1;
        public double FAILURE_COST = .2;

        // The state quality reduction factor for the waste generated by a country
        // If there are more electronic waste created by a country, it'll reduce the overall state quality more
        public double ELECTRONIC_WASTE_SQ_REDUCTIONFACTOR = .2;
        public double WASTE_MATERIAL_SQ_REDUCTIONFACTOR = .1;
    }
}
